[icons]
# font awesome
TelegramDesktop = ""
64Gram = ""
firefox = ""
cachy-browser = ""
Chromium = ""
Alacritty = ""
jetbrains-idea = ""
mpv = ""
obsidian =""
tidal-hifi = "󰝚"
cantata = "󰝚"
Signal = ""

[options]
remove_duplicates = true
no_names = false
no_icon_names = true
