[settings]
experimental = true
status = { missing_tools = "if_other_versions_installed", show_env = false, show_tools = true, truncate = false }
idiomatic_version_file_enable_tools = []

[settings.pipx]
uvx = true

[tools]
golangci-lint = "2.5.0"
clusterctl = "1.10.7"
helm = "3.18.4"
helmfile = "1.1.2"
kubectl = "1.32.8"
kubelogin = "latest"
pipx = "latest"
sops = "3.9.4"
usage = "latest"
crossplane = "latest"
kubebuilder = "latest"
go = "latest"
